parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    env(SPLASH_HOST): 'http://localhost:8000'

splash:
    ################################################################################
    # List of Available Connector Connections
    ################################################################################
    connections:

        ########################################################################
        # Faker Server
        standalone:
            id:                 "ThisIsFakerWsId"
            key:                "ThisIsNotASecretKeyForFaker"
            name:               "[Faker] Standalone"
            host:               "%env(SPLASH_HOST)%/ws/splash"
            server_host:        "%env(SPLASH_HOST)%"

        ########################################################################
        # Faker Connector
        connector:
            id:                 "ThisIsFakerConnectorWsId"
            key:                "ThisIsNotASecretKeyForFaker"
            name:               "[Faker] Connector"
            connector:          faker
            host:               "%env(SPLASH_HOST)%/ws/faker"
            server_host:        "%env(SPLASH_HOST)%"
