################################################################################
#
# * This file is part of SplashSync Project.
# *
# * Copyright (C) Splash Sync <www.splashsync.com>
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# *
# * For the full copyright and license information, please view the LICENSE
# * file that was distributed with this source code.
# *
# * @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Include Pipeline Templates
include:
  - remote: 'https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/gitlab/php/connectors.yaml'

################################################################
# Defined Pipeline Stages
stages:
  - Builds
  - Quality
  - Functional
#  - Builds

# Publishes a tag/branch to Composer Packages of the current project
publish:
    image: curlimages/curl:latest
    stage: Builds
    variables:
        URL: "$CI_SERVER_PROTOCOL://$CI_SERVER_HOST:$CI_SERVER_PORT/api/v4/projects/$CI_GROUP_ID/packages/composer?job_token=$CI_JOB_TOKEN"
    script:
        - version=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
        - insecure=$([ "$CI_SERVER_PROTOCOL" = "http" ] && echo "--insecure" || echo "")
        - response=$(curl -s -w "\n%{http_code}" $insecure --data $version $URL)
        - code=$(echo "$response" | tail -n 1)
        - body=$(echo "$response" | head -n 1)
        # Output state information
        - if [ $code -eq 201 ]; then
          echo "Package created - Code $code - $body";
          else
          echo "Could not create package - Code $code - $body";
          exit 1;
          fi
