################################################################################
#
# * This file is part of SplashSync Project.
# *
# * Copyright (C) Splash Sync <www.splashsync.com>
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# *
# * For the full copyright and license information, please view the LICENSE
# * file that was distributed with this source code.
# *
# * @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Defined Pipeline Stages
stages:
  - quality
  - functional
  - deploy

################################################################
# Base Job
################################################################

.base:    &base
    tags:
        - Dedicated
    before_script:
        ################################################################################
        # Install Symfony
        - composer update
    after_script:
        ################################################################################
        # Run After Script
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh

################################################################
# Quality Tests
################################################################

.quality:    &quality
    <<: *base
    stage:      quality
    script:
        # Execute Grumphp Testsuite
        - wall-e grumphp:quality
        - wall-e grumphp:stan

quality:php-8.1:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
    <<: *quality

quality:php-8.0:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
    <<: *quality

################################################################
# Functional Tests
################################################################

.functional:    &functional
    <<: *base
    stage:      functional
    script:
      # Execute PhpUnit Tests
      - vendor/bin/phpunit --log-junit $CI_PROJECT_DIR/full-report.xml
    artifacts:
      when: always
      reports:
        junit: "*-report.xml"

functional:php-8.1:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
    <<: *functional

functional:php-8.0:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
    <<: *functional

################################################################
# Build Documentation
################################################################
pages:
    image:      jekyll/minimal:latest
    stage:      deploy
    tags:       [ Dedicated ]
    ################################################################################
    # Run Test Script
    script:
        - wget -qO - https://gitlab.com/badpixxel-robo/jekyll/-/raw/main/scripts/gitlab-pages.sh | sh
    artifacts:
        paths:
            - public
