################################################################################
#
# * This file is part of SplashSync Project.
# *
# * Copyright (C) Splash Sync <www.splashsync.com>
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# *
# * For the full copyright and license information, please view the LICENSE
# * file that was distributed with this source code.
# *
# * @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Versions of PHP to test against
php:
    - "7.1"
    - "7.2"      
    - "7.3"      

################################################################################
# Install & Configure Environnement
install:
  ################################################################################
  # Setup Travis
  - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/travis/configure.sh | sh
  # Build Module (Composer)
  - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/travis/composer.sh | sh

################################################################################
# Run script
script:
    # Execute Grump Travis Testsuite 
    - php vendor/bin/grumphp run --testsuite=travis
    # With PHP 7 => Execute Grump CsFixer Testsuite 
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.0" ]]; then php vendor/bin/grumphp run --testsuite=csfixer; fi  
    # With PHP 7 => Execute Grump Phpstan Testsuite 
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.0" ]]; then php vendor/bin/grumphp run --testsuite=phpstan; fi

################################################################################
# Run After Script
after_script:
  - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/travis/after.sh | sh

################################################################################
# GENERIC CONFIGURATION
################################################################################

################################################################################
# Platform config
language: php
os: linux

################################################################################
# Start mysql service
services:
  - mysql

################################################################################
# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

################################################################################
# Define an environment variable
env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=disabled

################################################################################
# After a build, send email notification with the build results
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always