
################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
################################################################################

services:

    ################################################################################
    # PHP 8.3
    php-8.3:
        image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.3
        container_name: php-faker-8.3
        environment:
            COMPOSER_ROOT_VERSION:  dev-master
        volumes:
            - ./:/var/www/html
            - vendor-php83:/var/www/html/vendor

    ################################################################################
    # PHP 8.2
    php-8.2:
        image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2
        container_name: php-faker-8.2
        environment:
            COMPOSER_ROOT_VERSION:  dev-master
        volumes:
            - ./:/var/www/html
            - vendor-php82:/var/www/html/vendor

    ################################################################################
    # PHP 8.1
    php-8.1:
        image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
        container_name: php-faker-8.1
        environment:
            COMPOSER_ROOT_VERSION:  dev-master
        volumes:
            - ./:/var/www/html
            - vendor-php81:/var/www/html/vendor

    ################################################################################
    # PHP 8.0
    php-8.0:
        image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
        container_name: php-faker-8.0
        environment:
            COMPOSER_ROOT_VERSION:  dev-master
        volumes:
            - ./:/var/www/html
            - vendor-php80:/var/www/html/vendor

volumes:
    vendor-php83: ~
    vendor-php82: ~
    vendor-php81: ~
    vendor-php80: ~
