services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    ################################################################################
    # AutoWire for Controllers
    Splash\Connectors\Faker\Actions\:
        resource: '../../Actions'
        tags: ['controller.service_arguments', 'container.service_subscriber']

    ########################################################################
    # Splash Faker Standalone Events Listener for Symfony
    splash.connector.faker.events.symfony:
        class: Splash\Connectors\Faker\EventSubscriber\SymfonyEventsSubscriber
        tags:       ["kernel.event_subscriber"]

    ########################################################################
    # Splash Faker Standalone Events Listener for Doctrine
    splash.connector.faker.events.doctrine:
        class: Splash\Connectors\Faker\EventSubscriber\DoctrineEventsSubscriber
        arguments:  
            - "@splash.connectors.manager"
        tags:       ["doctrine.event_subscriber"]

    ########################################################################
    # Splash Faker Field Builder
    Splash\Connectors\Faker\Services\FieldsBuilder: ~

    ########################################################################
    # Splash Faker Generic Objects
    splash.connector.faker.object:
        class:      Splash\Connectors\Faker\Objects\Generic
        public:     true
        autowire:   true
        tags:
            # Register Faker Standalone Connector Objects           
            - { name: "splash.standalone.object", type : "short" }            
            - { name: "splash.standalone.object", type : "simple" }
            - { name: "splash.standalone.object", type : "primary" }
            - { name: "splash.standalone.object", type : "list" }
            - { name: "splash.standalone.object", type : "image" }
            # Register Faker Actions
            - { name: "splash.standalone.action", type : "master",      action: "\\Splash\\Connectors\\Faker\\Actions\\Master" }
            - { name: "splash.standalone.action", type : "index",       action: "\\Splash\\Connectors\\Faker\\Actions\\Master" }
            - { name: "splash.standalone.action", type : "validate",    action: "\\Splash\\Connectors\\Faker\\Actions\\Validate" }
            - { name: "splash.standalone.action", type : "invalidate",  action: "\\Splash\\Connectors\\Faker\\Actions\\Invalidate" }
            - { name: "splash.standalone.action", type : "fail",        action: "\\Splash\\Connectors\\Faker\\Actions\\Fail" }
            
    ########################################################################
    # Splash Faker Generic Widget
    splash.connector.faker.widget:
        class:      Splash\Connectors\Faker\Widgets\Generic
        public:     true
        autowire:   true
        tags:
            # Register Faker Standalone Connector Widget           
            - { name: "splash.standalone.widget", type : "Empty" }            
            - { name: "splash.standalone.widget", type : "Text" }            
            - { name: "splash.standalone.widget", type : "Notifications" }            
            - { name: "splash.standalone.widget", type : "Morris" }            
            
            
            