services:

    ########################################################################
    # Splash Faker Standalone Events Listner for Symfony
    splash.connector.faker.events.symfony:
        class: Splash\Connectors\FakerBundle\EventSubscriber\SymfonyEventsSubscriber
        arguments:  ["@=service('service_container').getParameter('splash_faker')"]
        tags:       ["kernel.event_subscriber"]

    ########################################################################
    # Splash Faker Standalone Events Listner for Doctrine
    splash.connector.faker.events.doctrine:
        class: Splash\Connectors\FakerBundle\EventSubscriber\DoctrineEventsSuscriber
        arguments:  
            - "@=service('service_container').getParameter('splash_faker')"
            - "@splash.connectors.manager"
        tags:       ["doctrine.event_subscriber"]

    ########################################################################
    # Splash Faker Field Buidler
    Splash\Connectors\FakerBundle\Services\FieldsBuilder:
        class: Splash\Connectors\FakerBundle\Services\FieldsBuilder
 
