services:

    ########################################################################
    # Splash Faker Standalone Events Listner for Symfony
    splash.connector.faker.events.symfony:
        class: Splash\Connectors\FakerBundle\EventSubscriber\SymfonyEventsSubscriber
        tags:       ["kernel.event_subscriber"]

    ########################################################################
    # Splash Faker Standalone Events Listner for Doctrine
    splash.connector.faker.events.doctrine:
        class: Splash\Connectors\FakerBundle\EventSubscriber\DoctrineEventsSuscriber
        arguments:  
            - "@splash.connectors.manager"
        tags:       ["doctrine.event_subscriber"]

    ########################################################################
    # Splash Faker Field Buidler
    Splash\Connectors\FakerBundle\Services\FieldsBuilder:
        class: Splash\Connectors\FakerBundle\Services\FieldsBuilder
 
    ########################################################################
    # Splash Faker Generic Objects
    splash.connector.faker.object:
        class:      Splash\Connectors\FakerBundle\Objects\Generic
        public:     true
        autowire:   true
        tags:
            # Register Faker Standalone Connector Objects           
            - { name: "splash.standalone.object", type : "short" }            
            - { name: "splash.standalone.object", type : "simple" }
            - { name: "splash.standalone.object", type : "list" }
            - { name: "splash.standalone.object", type : "image" }
            # Register Faker Actions
            - { name: "splash.standalone.action", type : "master",      action: "SplashFakerBundle:Actions:master"}
            - { name: "splash.standalone.action", type : "index",       action: "SplashFakerBundle:Actions:index"}
            - { name: "splash.standalone.action", type : "validate",    action: "SplashFakerBundle:Actions:validate"}
            - { name: "splash.standalone.action", type : "invalidate",  action: "SplashFakerBundle:Actions:invalidate"}
            - { name: "splash.standalone.action", type : "fail",        action: "SplashFakerBundle:Actions:fail"}
            
    ########################################################################
    # Splash Faker Generic Widget
    splash.connector.faker.widget:
        class:      Splash\Connectors\FakerBundle\Widgets\Generic
        public:     true
        autowire:   true
        tags:
            # Register Faker Standalone Connector Widget           
            - { name: "splash.standalone.widget", type : "Empty" }            
            - { name: "splash.standalone.widget", type : "Text" }            
            - { name: "splash.standalone.widget", type : "Notifications" }            
            - { name: "splash.standalone.widget", type : "Morris" }            
            
            
            